# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/mnt/disk2/PycharmProjects/ISAT_with_segment_anything/ISAT/ui/Converter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 680)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Dialog.setFont(font)
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Converter"))
        # self.pushButton_coco2isat_coco_json_path.setText(_translate("Dialog", "json path"))
        # self.lineEdit_coco2isat_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons save root"))
        # self.lineEdit_coco2isat_coco_json_path.setPlaceholderText(_translate("Dialog", "COCO json path"))
        # self.pushButton_coco2isat_isat_json_root.setText(_translate("Dialog", "save root"))
        # self.checkBox_coco2isat_keep_crowd.setText(_translate("Dialog", "keep crowd"))
        # self.toolBox_coco.setItemText(self.toolBox_coco.indexOf(self.toolbox_item_coco2isat), _translate("Dialog", "COCO to ISAT"))
        # self.lineEdit_isat2coco_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons root"))
        # self.pushButton_isat2coco_isat_json_root.setText(_translate("Dialog", "json root"))
        # self.lineEdit_isat2coco_coco_json_path.setPlaceholderText(_translate("Dialog", "COCO json save path"))
        # self.pushButton_isat2coco_coco_json_path.setText(_translate("Dialog", "save path"))
        # self.checkBox_isat2coco_keep_crowd.setText(_translate("Dialog", "keep crowd"))
        # self.toolBox_coco.setItemText(self.toolBox_coco.indexOf(self.toolbox_item_isat2coco), _translate("Dialog", "ISAT to COCO"))
        # self.label_2.setText(_translate("Dialog", "COCO save annotations to a single JSON file."))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_COCO), _translate("Dialog", "COCO"))
        # self.lineEdit_yolo2isat_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons save root"))
        # self.pushButton_yolo2isat_isat_json_root.setText(_translate("Dialog", "save root"))
        # self.lineEdit_yolo2isat_yolo_txt_root.setPlaceholderText(_translate("Dialog", "YOLO txts root"))
        # self.pushButton_yolo2isat_yolo_txt_root.setText(_translate("Dialog", "txt root"))
        # self.lineEdit_yolo2isat_yolo_image_root.setPlaceholderText(_translate("Dialog", "YOLO images root"))
        # self.pushButton_yolo2isat_yolo_image_root.setText(_translate("Dialog", "image root"))
        # self.lineEdit_yolo2isat_yolo_cate_path.setPlaceholderText(_translate("Dialog", "YOLO category file path.(Txt file with one line for one category.)  "))
        # self.pushButton_yolo2isat_yolo_cate_path.setText(_translate("Dialog", "category file"))
        # self.label.setText(_translate("Dialog", "*"))
        # self.label_7.setText(_translate("Dialog", "*"))
        # self.label_9.setText(_translate("Dialog", "*"))
        # self.toolBox_yolo.setItemText(self.toolBox_yolo.indexOf(self.toolbox_item_yolo2isat), _translate("Dialog", "YOLO to ISAT"))
        # self.pushButton_isat2yolo_yolo_txt_root.setText(_translate("Dialog", "save root"))
        # self.lineEdit_isat2yolo_yolo_txt_root.setPlaceholderText(_translate("Dialog", "YOLO txts save root"))
        # self.lineEdit_isat2yolo_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons root"))
        # self.pushButton_isat2yolo_isat_json_root.setText(_translate("Dialog", "json root"))
        # self.toolBox_yolo.setItemText(self.toolBox_yolo.indexOf(self.toolbox_item_isat2yolo), _translate("Dialog", "ISAT to YOLO"))
        # self.label_3.setText(_translate("Dialog", "YOLO save annotations to multiple TXT files."))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_YOLO), _translate("Dialog", "YOLO"))
        # self.pushButton_labelme2isat_labelme_json_root.setText(_translate("Dialog", "json root"))
        # self.lineEdit_labelme2isat_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons save root"))
        # self.lineEdit_labelme2isat_labelme_json_root.setPlaceholderText(_translate("Dialog", "LABELME jsons root"))
        # self.pushButton_labelme2isat_isat_json_root.setText(_translate("Dialog", "save root"))
        # self.toolBox_labelme.setItemText(self.toolBox_labelme.indexOf(self.toolbox_item_labelme2isat), _translate("Dialog", "LABELME to ISAT"))
        # self.lineEdit_isat2labelme_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons root"))
        # self.pushButton_isat2labelme_isat_json_root.setText(_translate("Dialog", "json root"))
        # self.lineEdit_isat2labelme_labelme_json_root.setPlaceholderText(_translate("Dialog", "LABELME jsons save root"))
        # self.pushButton_isat2labelme_labelme_json_root.setText(_translate("Dialog", "save root"))
        # self.toolBox_labelme.setItemText(self.toolBox_labelme.indexOf(self.toolbox_item_isat2labelme), _translate("Dialog", "ISAT to LABELME"))
        # self.label_4.setText(_translate("Dialog", "LABELME save annotations to multiple JSON files. (When convert LABELME to ISAT for instance segmentation, labelme group id must>0.)"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_LABELME), _translate("Dialog", "LABELME"))
        # self.pushButton_isat2voc_voc_png_root.setText(_translate("Dialog", "save root"))
        # self.lineEdit_isat2voc_voc_png_root.setPlaceholderText(_translate("Dialog", "VOC pngs save root"))
        # self.lineEdit_isat2voc_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons root"))
        # self.pushButton_isat2voc_isat_json_root.setText(_translate("Dialog", "json root"))
        # self.checkBox_is_instance.setText(_translate("Dialog", "is instance"))
        # self.label_5.setText(_translate("Dialog", "VOC save annotations to multiple PNG files."))
        # self.label_10.setText(_translate("Dialog", "**The num of classification and the group must in [0, 255]**"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_VOC), _translate("Dialog", "VOC"))
        # self.lineEdit_isat2vocod_isat_json_root.setPlaceholderText(_translate("Dialog", "ISAT jsons root"))
        # self.pushButton_isat2vocod_isat_json_root.setText(_translate("Dialog", "json root"))
        # self.lineEdit_isat2vocod_voc_xml_root.setPlaceholderText(_translate("Dialog", "VOC xmls save root"))
        # self.pushButton_isat2vocod_voc_xml_root.setText(_translate("Dialog", "save root"))
        # self.label_6.setText(_translate("Dialog", "VOC save annotations to multiple XML files for object detection."))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_VOC_DETECTION), _translate("Dialog", "VOC for object detection"))
        # self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
        # self.pushButton_convert.setText(_translate("Dialog", "Convert"))